name: Dependency Check

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 12 * * 1'  # Run at 12:00 UTC every Monday
  workflow_dispatch:
    # Allow manual triggering

jobs:
  scan-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Check for vulnerable dependencies
      run: |
        safety check --full-report
        
    - name: Check for outdated dependencies
      run: |
        pip list --outdated
